import type { GetStaticPaths, GetStaticProps, NextPage } from "next";

import Head from "next/head";
import { PrismaClient } from "@prisma/client";
import path from "path";
import { processor } from "../lib/org-parser";

const client = new PrismaClient();

const getPageFile = (file?: string) =>
  path.join(process.cwd(), "data", file ?? "");

const getPages = async () => {
  const pages = await client.orgPage.findMany();
  return pages.map((page) => page.slug);
};

export const getStaticPaths: GetStaticPaths = async () => {
  const slugs = await getPages();

  return {
    paths: slugs.map((slug) => ({ params: { slug } })),
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const slug = (params?.slug ?? "") as string;
  const dbItem = await client.orgPage.findFirst({
    where: { slug },
  });

  const data = processor.processSync(dbItem?.content ?? "").value.toString();

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage<{ data: string }> = ({ data }) => {
  // console.log(processor.processSync(data));
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-6 max-w-2xl mx-auto">
        <div className="flex flex-col space-y-3">
          <h1 className="text-5xl font-extrabold">Journal</h1>
          <span>Kyle Pfromer</span>
        </div>

        <hr className="my-6" />

        <div
          className="mx-auto prose max-w-none"
          dangerouslySetInnerHTML={{
            __html: data,
          }}
        />
      </main>
    </div>
  );
};

export default Home;
