import type { GetStaticProps, NextPage } from "next";
import { processor, testProcessor } from "../lib/org-parser";

import Head from "next/head";
import { promises as fs } from "fs";
import path from "path";

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const rawData = await fs.readFile(path.join(process.cwd(), "data/test.org"));
  const data = rawData.toString();

  return {
    props: {
      data: (await processor.process(data)).value.toString(),
    },
  };
};

const Home: NextPage<{ data: string }> = ({ data }) => {
  // console.log(processor.processSync(data));
  // console.log(testProcessor.processSync(data));
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-6 max-w-2xl mx-auto">
        <div className="flex flex-col space-y-3">
          <h1 className="text-5xl font-extrabold">Journal</h1>
          <span>Kyle Pfromer</span>
        </div>

        <hr className="my-6" />

        <div
          className="mx-auto prose max-w-none"
          dangerouslySetInnerHTML={{
            __html: data,
          }}
        />
      </main>
    </div>
  );
};

export default Home;
