import type { GetServerSideProps, NextPage } from "next";

import Head from "next/head";
import { getPageContentBySlug } from "../lib/org/page";
import { useRouter } from "next/dist/client/router";

export const getServerSideProps: GetServerSideProps = async () => {
  const data = await getPageContentBySlug("default");

  if (data === undefined) {
    return { notFound: true };
  }

  return {
    props: {
      data,
    },
  };
};

const Home: NextPage<{ data: string }> = ({ data }) => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="pt-6 max-w-2xl mx-auto">
        <div className="flex flex-col space-y-3">
          <h1 className="text-5xl font-extrabold">Journal</h1>
          <span>Kyle Pfromer</span>
        </div>
        <hr className="my-6" />
        {router.isFallback ? (
          <div className="mx-auto prose max-w-none">Loading...</div>
        ) : (
          <div
            className="mx-auto prose max-w-none"
            dangerouslySetInnerHTML={{
              __html: data,
            }}
          />
        )}
      </main>
    </div>
  );
};

export default Home;
